### ISSUE TITLE
ValueError: unknown link chunk b'N'/v12

### ISSUE THREAD

**Issue by SaltfishAmi** [grawity/obml-parser#2]
```
$ ./obml-parser *.obml
file = 1e93099c.obml
version = 12
--- metadata [88] ---
--- metadata [191] ---
--- metadata [200] ---
section 1 ends at 204
--- links [204] ---
Traceback (most recent call last):
  File "./obml-parser", line 531, in <module>
    for item in parse_file(arg):
  File "./obml-parser", line 323, in parse_file
    raise ValueError("unknown link chunk %r/v%r" % (type, version))
ValueError: unknown link chunk b'N'/v12
```

The file sample is: [1e93099c.zip](https://github.com/grawity/obml-parser/files/8948713/1e93099c.zip)

Other webpages saved by the same Opera Mini instance were converted successfully, but this failed. It is a Traditional Chinese (Taiwan) webpage with unknown character encoding.

**Comment by grawity** [comment]
Looks like this type is already ignored for other versions, so it should be fine to ignore it for v12 as well (for now).

The original character encoding doesn't matter – all pages get converted to UTF-8 by Opera servers when they're rendered to OBML.

**Comment by grawity** [comment]
Looking at it closer, 'N' seems to be an internal anchor link (the "Top" link at the very bottom of the page). I'll try to figure out how it stores the coordinates...

**Comment by grawity** [comment]
Okay, the "Top" link should actually work now.
